In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
scalar = tf.constant(9)
scalar
#create a tensor 0-dim

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([9, 9])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 9], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[9, 9], [9, 9]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[9., 9., 9.], [9., 9., 9.], [9., 9., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14 ,15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
changeable_tensor = tf.Variable([9, 9]) #it changes
unchangeable_tensor = tf.constant([9, 9]) #it doesn't change
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 9], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 9], dtype=int32)>)

In [ ]:
#change elements
changeable_tensor[0].assign(7)
#change elements (does not work) -> changeable_tensor[0] = 7

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 9], dtype=int32)>

In [ ]:
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
#sheefle a tensor ( valuable for when you want to sheffle ur data so the inherent order does not effect learning)
not_shuffled = tf.constant([[3, 4], [13, 9], [29, 2]])
not_shuffled.ndim
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [13,  9],
       [29,  2]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13,  9],
       [29,  2],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[29,  2],
       [13,  9],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [13,  9],
       [29,  2]], dtype=int32)>

In [ ]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)


In [ ]:
print(tf.random.uniform([1]))  # generates 'A3'
print(tf.random.uniform([1]))  # generates 'A4'

tf.Tensor([0.7413678], shape=(1,), dtype=float32)
tf.Tensor([0.7402308], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [ ]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'


(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)


In [ ]:
tf.random.set_seed(42) #global level
tf.random.shuffle(not_shuffled, seed=42) #ops level

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [13,  9],
       [29,  2]], dtype=int32)>

In [ ]:
#other ways to make tensors

In [ ]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#numpy arrays into tensors -> 

numpy arrays into tensors -> the main difference between numpy arrays n tensorflow is the tensors can be run on a gpu

In [ ]:
import numpy as np
numpy_a = np.arange(1, 25, dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
a = tf.constant(numpy_a, shape=(2, 3, 4))
a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

getting information from tensors

> shape -> tensor.shape
> rank -> tensor.ndom
> axis -> tensor[0], tensor[:, 1]
> size -> tf.size(tensor)



In [ ]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[:, 0]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("elements along the 0 axis: ", rank_4_tensor.shape[0])
print("elements along the last axis:", rank_4_tensor.shape[-1])

elements along the 0 axis:  2
elements along the last axis: 5


In [ ]:
print("total elements: ", tf.size(rank_4_tensor))
print("total elements: ", tf.size(rank_4_tensor).numpy())

total elements:  tf.Tensor(120, shape=(), dtype=int32)
total elements:  120


In [ ]:
rank_4_tensor[:2, :2, :2, :2] # tf.zeros([2, 3, 4, 5])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :1]
rank_4_tensor[:1, :1, :1, :] #same as above

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10, 7], [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # Spread operator
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[:, tf.newaxis, :]
rank_3_tensor

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1) # same as above '-1' means expand final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

Tensor operations

In [ ]:
tensor = tf.constant([[10, 7], [3, 4]])
#tensor + 10
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#tensor * 10
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#tensor / 10
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
#tensor - 10
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

**Matrix multiplication**

in machine learning, matrix mult is one of the most common operations

In [ ]:
#print(tensor)
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
mm = tf.constant([[[1, 2, 5], [7, 2, 1], [3, 3, 3]]])
mm

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]]], dtype=int32)>

In [ ]:
mn = tf.constant([[[3, 5], [6, 7], [1, 8]]])
mn

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[3, 5],
        [6, 7],
        [1, 8]]], dtype=int32)>

In [ ]:
tf.matmul(mm, mn)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [ ]:
mm @ mn

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [ ]:
X = tf.constant([[2, 0], [2, 10], [1, 9]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  0],
       [ 2, 10],
       [ 1,  9]], dtype=int32)>

In [ ]:
Y = tf.constant([[8, 2], [2, 5], [1, 2]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[8, 2],
       [2, 5],
       [1, 2]], dtype=int32)>

In [ ]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16,  4,  4],
       [66, 14, 24],
       [53, 11, 20]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[16,  4,  4],
       [66, 14, 24],
       [53, 11, 20]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18,  8],
       [91, 43]], dtype=int32)>

In [ ]:
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  0],
        [ 2, 10],
        [ 1,  9]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 2,  2,  1],
        [ 0, 10,  9]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 2,  0,  2],
        [10,  1,  9]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(X), Y), tf.matmul(X, tf.transpose(Y))


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[21, 16],
        [29, 68]], dtype=int32)>, <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[16,  4,  2],
        [36, 54, 22],
        [26, 47, 19]], dtype=int32)>)

In [ ]:
tf.reshape(X, shape=(2, 3)), tf.transpose(X), X

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 2,  0,  2],
        [10,  1,  9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 2,  2,  1],
        [ 0, 10,  9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  0],
        [ 2, 10],
        [ 1,  9]], dtype=int32)>)

**the dot product**

matrix mult is also referred to as the dot product

u can perform matrix mult using:
* `tf.matmul()`
* `tf.tensordot()`


In [ ]:
# performer the dot product on X n Y (requires X or Y to be transposed)
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  0],
        [ 2, 10],
        [ 1,  9]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[8, 2],
        [2, 5],
        [1, 2]], dtype=int32)>)

In [ ]:
tf.tensordot(v(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 16],
       [29, 68]], dtype=int32)>

generally when performing matrix mult on two tensors and one of the axes does not line up you will transpose rather reshape to get satisfy the matrix multiplication rules

In [ ]:
# create a new tensor with default datatype (float32)
B = tf.constant([1, 8, 1, 9.0])
B.dtype

tf.float32

In [ ]:
# change from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1., 8., 1., 9.], dtype=float16)>

In [ ]:
D, D.dtype

(<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1., 8., 1., 9.], dtype=float16)>,
 tf.float16)

In [ ]:
# change from int32 to float32
C = tf.constant([1, 2, 3])
C.dtype

tf.int32

In [ ]:
# change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E.dtype

tf.float32

### Aggregating tensors

Aggegating tensors = condensing them from mult values down to a smaller amount of values

In [ ]:
# get the absolute values
F = tf.constant([-7, -10])
tf.abs(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
G = tf.constant(np.random.randint(0, 100, size=50))
G

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([27, 89, 51, 61, 74, 81, 68, 39, 33, 60, 67, 77, 58,  6, 28, 27, 56,
       78, 51, 14, 44, 17, 36, 94, 25, 82, 24,  7,  5, 63,  5, 87, 54, 31,
       64,  2, 76,  4, 25, 14,  2,  8, 22, 11, 53, 18,  4, 77, 32, 14])>

In [ ]:
print(tf.reduce_min(G))
print(tf.reduce_max(G))
print(tf.reduce_mean(G))
print(tf.reduce_sum(G))

tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(94, shape=(), dtype=int64)
tf.Tensor(40, shape=(), dtype=int64)
tf.Tensor(2045, shape=(), dtype=int64)


In [ ]:
# find the variance of our tensor
import tensorflow_probability as tfp
tfp.stats.variance(G)

<tf.Tensor: shape=(), dtype=int64, numpy=781>

In [ ]:
# standart deviation
tf.math.reduce_std(tf.cast(G, dtype=tf.float32)) #it works just to float tensors

<tf.Tensor: shape=(), dtype=float32, numpy=27.939398>

# find the positional minimum n maximum of a tensor (argmin n argmax)

In [ ]:
tf.random.set_seed(42)
I = tf.random.uniform(shape=[50])
I

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# max
tf.argmax(I) # same as np.argmax() // return position

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest value position
I[tf.argmax(I)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(I)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
I[tf.argmax(I)] == tf.reduce_max(I)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(I)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
I[tf.argmin(I)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
I[tf.argmin(I)] == tf.reduce_min(I)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.random.set_seed(42)
J = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 1, 50])
J

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [ ]:
J_squeezed = tf.squeeze(J) #remove dimensions of size 1 from the shape of tensor
J_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#one-hot encoding tensor
some_list = [0, 1, 2, 3] #could be red, green, blue, purple

#one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=4, on_value="on value", off_value="off value")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'on value', b'off value', b'off value', b'off value'],
       [b'off value', b'on value', b'off value', b'off value'],
       [b'off value', b'off value', b'on value', b'off value'],
       [b'off value', b'off value', b'off value', b'on value']],
      dtype=object)>

# Tensors and Numpy

In [ ]:
#create a tensor directly from a numpy array
A = tf.constant(np.array([3., 7., 10.]))
A

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J), type(np.array(J))

(array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
       dtype=float32), numpy.ndarray)

In [ ]:
#convert tensor A to a numpy array
A.numpy(), type(A.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# the default types of each are slightly different
numpy_A = tf.constant(np.array([3., 7., 10.]))
tensor_A = tf.constant([3., 7., 10.])

numpy_A.dtype, tensor_A.dtype

(tf.float64, tf.float32)

# finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sun Dec 18 07:51:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P0    29W /  70W |    314MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> if u have access to a CUDA-enabled GPU, tensorflow will automatically use it whenever is possible