In [ ]:
import tensorflow as tf
print(tf.__version__)
# https://github.com/mrdbourke/tensorflow-deep-learning#-00-tensorflow-fundamentals-exercises

2.9.2


In [ ]:
# Create a vector, scalar, matrix and tensor with values of your choosing using
scalar = tf.constant([2.])
vetor = tf.constant([2., 1., 3.])
matrix = tf.constant([[2., 3.], [4., 5.]])
tensor = tf.constant([[[2., 3.], [4., 5.]], [[2., 3.], [4., 5.]]])
scalar, vetor, matrix, tensor

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 1., 3.], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 3.],
        [4., 5.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
 array([[[2., 3.],
         [4., 5.]],
 
        [[2., 3.],
         [4., 5.]]], dtype=float32)>)

In [ ]:
# Find the shape, rank and size of the tensors you created in 1.
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 2, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=8>)

In [ ]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300].
random_1 = tf.random.Generator.from_seed(42)
tensor = random_1.normal(shape=(5, 6))
tensor_random = random_1.normal(shape=(5, 300))
tensor_random

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[-0.7484593 ,  0.2261784 ,  0.88003373, ...,  0.01979171,
         1.6340615 ,  0.06231747],
       [ 0.39519766, -0.4240933 , -0.05865003, ...,  0.9310478 ,
         1.0119863 ,  1.5864458 ],
       [ 0.24623345,  0.24604762, -0.81141615, ..., -1.1121045 ,
         0.37668166,  0.29014483],
       [ 2.2517543 ,  0.41579473,  1.7317932 , ...,  0.35263988,
        -0.48368332,  0.5451762 ],
       [-0.37476325,  0.5898619 , -0.54519105, ..., -0.68319434,
         0.3706781 ,  0.5888639 ]], dtype=float32)>

In [ ]:
# Multiply the two tensors you created in 3 using matrix multiplication.
tensor_mult = tf.multiply(tensor, 3)
tensor_random_mult = tf.multiply(tensor_random, 3)
tensor_mult

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[-2.2697408 , -0.20564106,  0.22785076, -3.7721534 , -0.6958129 ,
        -5.432357  ],
       [ 0.29966182, -1.5299594 , -2.2607415 , -1.7149885 ,  0.4442322 ,
        -0.70088977],
       [-1.0568388 ,  1.218638  , -3.1570525 ,  3.6163793 ,  5.0623465 ,
        -1.3388925 ],
       [-7.0232525 ,  2.9702725 , -0.2628969 , -1.9067041 , -1.8485209 ,
        -5.8324394 ],
       [-1.4487902 , -1.5734242 , -3.1035986 ,  3.9200702 , -4.5553718 ,
        -1.3755633 ]], dtype=float32)>

In [ ]:
# Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tf.transpose(tensor_random), tensor, axes=1)

<tf.Tensor: shape=(300, 6), dtype=float32, numpy=
array([[-4.5715604 ,  2.3757777 , -0.4234044 , -0.9088368 , -0.17078751,
        -3.0528276 ],
       [-1.5584338 ,  0.4030325 , -0.56883025,  0.7611466 , -0.85194707,
        -1.4991201 ],
       [-4.176814  ,  1.6405511 ,  1.3771878 , -3.8642101 , -1.821257  ,
        -4.334595  ],
       ...,
       [-0.02582704, -0.22046563,  1.1460923 , -3.0145786 , -0.92322874,
        -0.12935428],
       [-0.3145796 , -1.1483982 , -1.3759993 , -1.3873088 ,  0.14165701,
        -2.5930896 ],
       [-1.551578  , -0.46454734, -2.15309   , -0.2125451 , -0.52002037,
        -1.9428847 ]], dtype=float32)>

In [ ]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor_random = random_1.normal(shape=(224, 224, 3))
tensor_random

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 1.5124120e+00, -1.2635043e-01, -9.1112047e-01],
        [ 5.8041072e-01,  9.5609361e-03, -1.0261441e+00],
        [ 2.1184323e+00, -4.1609994e-01, -2.3780319e-01],
        ...,
        [ 5.3611922e-01,  3.1653297e-01,  7.7266502e-01],
        [ 2.1834375e-01, -8.1255299e-01,  1.4395438e+00],
        [-9.7088002e-02,  2.1730880e-01,  1.9694003e-01]],

       [[-1.9373918e+00,  2.8596404e-01, -1.3262355e+00],
        [-8.5901791e-01, -1.7938073e+00,  7.9750073e-01],
        [ 1.3391761e-01, -9.7046435e-01,  1.1993530e+00],
        ...,
        [-3.4664026e-01,  4.1245568e-01,  2.3257063e-01],
        [-9.3572694e-01, -9.4296944e-01,  6.3970315e-01],
        [ 1.3009294e+00,  1.5682887e-01,  6.1481422e-01]],

       [[ 4.2252064e-01,  1.5388216e+00, -1.8056948e+00],
        [ 4.3761440e-02,  1.4905982e-01,  1.2138206e+00],
        [-1.4910281e-01,  5.2283281e-01,  8.4488951e-02],
        ...,
        [-6.8292618e-01, -6.6977

In [ ]:
# Find the min and max values of the tensor you created in 6 along the first axis
tf.argmax(tensor_random, axis=1)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[152, 187, 190],
       [196,  13, 130],
       [157,  32,  73],
       [106, 209, 159],
       [198,  52, 113],
       [ 14,  15, 208],
       [ 67, 185,  68],
       [115, 189, 216],
       [ 90, 172, 223],
       [169, 132,  28],
       [124, 108, 221],
       [ 35, 157, 150],
       [  5, 123,  95],
       [106, 223,  10],
       [ 36, 126,   2],
       [ 67,  12,   1],
       [ 97, 218, 144],
       [ 63, 147,  83],
       [ 88, 144, 100],
       [153, 111, 172],
       [103, 175, 218],
       [ 95,  40,  41],
       [199,  50,  82],
       [ 65,  68,  86],
       [ 56, 148, 174],
       [106, 176, 193],
       [198, 162,  79],
       [184, 221,  48],
       [ 73, 146,  30],
       [ 35,  30,  30],
       [ 22, 148, 143],
       [ 82,  32, 171],
       [123,  16,  26],
       [ 48,  26,  35],
       [163,  89,   6],
       [148,  42, 104],
       [ 17, 110,  93],
       [204, 177, 188],
       [  0,   1, 136],
       [103, 214

In [ ]:
tf.argmin(tensor_random, axis=1)

<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
array([[147, 193, 168],
       [174, 123, 196],
       [195,  38,  77],
       [160,  13, 161],
       [139,  77, 145],
       [204, 153,  56],
       [ 78,  18, 141],
       [165, 136, 155],
       [128, 142, 196],
       [ 15,  67,  11],
       [189,  94,  69],
       [105, 194, 134],
       [ 74, 132, 169],
       [  7,  58, 198],
       [156,  65,  26],
       [145,  34,   2],
       [ 99,  60, 201],
       [ 44, 156, 130],
       [ 19, 188,  57],
       [185, 169, 187],
       [221, 189,  63],
       [112,  73, 120],
       [ 62,  55,  44],
       [223,  43,  33],
       [ 78, 120, 152],
       [ 98, 213, 102],
       [128,  89, 190],
       [128,  82,  38],
       [106,  22,  47],
       [ 17,  33, 127],
       [147, 151, 114],
       [197, 177, 218],
       [135, 134, 217],
       [216, 197, 140],
       [202,  86,   3],
       [169, 213,  35],
       [109, 207,  79],
       [ 75, 175, 213],
       [146,  24, 149],
       [ 35, 141

In [ ]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor_random2 = random_1.normal(shape=(1, 224, 224, 3))
tensor_random2

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[-0.6071416 , -0.3188059 ,  2.3023772 ],
         [-0.22674875, -0.6143498 , -0.33390504],
         [ 2.7506068 , -0.12808917,  0.8828583 ],
         ...,
         [ 1.409344  ,  1.7767879 ,  1.249777  ],
         [ 0.57180667, -0.21818577,  1.4720641 ],
         [-1.2454487 , -0.25244576, -1.5324352 ]],

        [[ 0.81377655,  1.300385  ,  0.16682354],
         [-1.1635808 , -1.3359034 ,  0.07381317],
         [-2.421398  ,  1.1073356 ,  0.5953532 ],
         ...,
         [-0.8218968 ,  0.06359439, -0.5143317 ],
         [ 0.30922726,  1.6862807 , -1.815716  ],
         [-0.31819245,  1.0350509 , -0.12154241]],

        [[ 0.46223915, -1.0214123 ,  0.6185009 ],
         [-0.45448717, -0.71041805, -0.95760006],
         [-2.1685688 ,  0.3955757 ,  0.6301875 ],
         ...,
         [-0.7537178 ,  0.4252425 , -0.6447862 ],
         [ 0.62141603, -0.7830902 , -2.000086  ],
         [-0.34533674, -0.28324974,  2.2232425

In [ ]:
J_squeezed = tf.squeeze(tensor_random2) #remove dimensions of size 1 from the shape of tensor
J_squeezed.shape

TensorShape([224, 224, 3])

In [ ]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tf.random.set_seed(42)
J = tf.constant(tf.random.uniform(shape=[10], maxval=37, dtype=tf.int32))
J

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 6, 20,  9, 15, 24, 15, 31, 27, 15, 10], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
h = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 2, 25])
h

<tf.Tensor: shape=(1, 1, 2, 25), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
         [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [ ]:
some_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
tf.argmax(J), J[tf.argmax(J)]

(<tf.Tensor: shape=(), dtype=int64, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=31>)

In [ ]:
# One-hot encode the tensor you created in 9.
tf.one_hot(J, depth=10, on_value=1., off_value=0.) # always expects int values

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>